### PR TITLE
Added: Ability to specify silent clusters and show it on the main page

### PR DESCRIPTION
**Pull request by Maix0**
This simple commit allows to specify silent clusters on the main tab.
I didn't change the view on the kiosk page since I don't know if it is wanted.

Currently the silent clusters are hardcoded into the <map>.py file, as a new key named "silent" that takes names of every clusters.  (edited each map file to have empty list except for paris(new) where I put paul-f3)

I used the fontawesome volume-xmark icon since it was already included.

Cheers :D

### CODE REVIEW

**Comment by wow0000** [comment]
Hello, could you please reformat your commit to only use tabulations and could you add a screenshot of the changes on mobile + desktop ? Could you please also add made-f0d to the silent list?

**Comment by Maix0** [comment]
Hi, I update so the silent cluster must be updated throught the admin panel, like the piscines clusters.
This also require a new table that is basically a clone of the PISCINES table, but named SILENTS.
All the code is basically copied from the piscines code.

There is also a space between both icons when both are present, so it is easier to read.
Here are some image:
Desktop:
image
Mobile:
image

Currently the SILENTS table has to be create manually since I didn't see where the database creation happens, but i'll gladly update the PR with such code if you point me at the code.

here is the code that create the SILENTS table:
```sql
create table SILENTS
(
    id      INTEGER
        primary key,
    campus  INTEGER default 1,
    cluster TEXT
);
```

**Comment by Maix0** [comment]
I saw that the kiosk mode also shows the icons so i'll add it to the PR asap.
Seeing that the whole building gets flag if a single cluster is flagged as a piscine i'll have to make sure that it doesn't also happen with the silent icon

**Comment by wow0000** [comment]
thank you for the contribution ! :)

**Pull request merged**
